command:
  command: holiday-hunter
  description: 'Hunt for the holiday'
  format: '/holiday-hunter '
  aliases:
    - 'h-h'
    - 'hh'
start-hunt:
  - 'fly %player%'
end-hunt:
  - 'fly %player%'
heads:
  turkey: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA2NTU1NzA2YjY0MWZkYWY0MzZjMDc2NjNmOTIzYWZjNWVlNzIxNDZmOTAxOTVmYjMzN2I5ZGU3NjY1ODhkIn19fQ=="